[project]
name = "maa-linux-remotecontrol"
version = "0.2.0"
description = "MAA Remote Control Client for Linux with head-less device"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
	"json5>=0.14.0",
	"loguru>=0.7.3",
	"opencv-python-headless>=4.11.0.86",
	"orjson>=3.10.15",
	"PyYAML>=6.0.2",
	"requests>=2.32.3",
	"websocket-client>=1.8.0",
]

[tool.ruff]
line-length = 160
unsafe-fixes = true

[tool.ruff.format]
indent-style = "tab"
quote-style = "double"

[tool.ruff.lint]
select = ["E", "F", "W"]
ignore = ["E501", "W191", "E101"]
fixable = ["ALL"]
unfixable = []